In [1]:
from pycozo.client import Client
import pandas as pd
from pycozo.client import Client
client = Client('rocksdb', 'snbsf1.db')

In [2]:
res = client.run("?[n]:= *reified_node[n]")
res

                     n
0       35184372090193
1       35184372090194
2       35184372090195
3       35184372090196
4       35184372090197
...                ...
410194  35184372500387
410195  35184372500388
410196  35184372500389
410197  35184372500390
410198  35184372500391

[410199 rows x 1 columns]

In [9]:
rn_df = pd.DataFrame(client.run("?[id_rn] := *reified_node[id_rn]"))
max_id = int(rn_df["id_rn"].max())
NEXT_RN = max_id + 1
NEXT_RN

35184372282716

In [2]:
import pandas as pd
from math import ceil

CHUNK_SIZE = 10000  

#Charger les données existantes dans des df
edge_df        = pd.DataFrame(client.run('?[id_e, ns, nd] := *edge[id_e, ns, nd]'))
edge_label_df  = pd.DataFrame(client.run('?[id_e, ln] := *edge_label[id_e, ln]'))
node_label_df  = pd.DataFrame(client.run('?[id_n, l] := *node_label[id_n, l]'))
reified_node_df= pd.DataFrame(client.run('?[id_rn] := *reified_node[id_rn]'))
n_con_node_df  = pd.DataFrame(client.run('?[id_rn, id_n] := *n_composed_of_node[id_rn, id_n]'))
n_con_edge_df  = pd.DataFrame(client.run('?[id_rn, id_e] := *n_composed_of_edge[id_rn, id_e]'))
node_prop_df   = pd.DataFrame(client.run('?[id_n, key, val] := *node_prop[id_n, key, val]'))

#Filtrer les arêtes hasMember
has_member_df = edge_label_df[edge_label_df['ln'] == 'hasMember'].merge(edge_df, on='id_e')

#Grouper par forum
forums = has_member_df.groupby('ns')  # ici ns = forum id

#initialiser des IDs réifiés
next_rn = reified_node_df['id_rn'].max() + 1 

new_reified_nodes = []
new_node_labels   = []
new_n_con_nodes   = []
new_n_con_edges   = []
new_node_props    = []

for forum_id, group in forums:
    rn_id = next_rn
    next_rn += 1
    
    #Reified node 
    new_reified_nodes.append([rn_id])
    
    # Node label 
    new_node_labels.append([rn_id, "forumMembership"])
    
    #Composed of edges (all hasMember edges for this forum) 
    for edge_id in group['id_e']: # ici id_e sont les ids des edges qui concernenet un forum identifié par forum_id
        new_n_con_edges.append([rn_id, edge_id])
    
    # Composed of nodes (forum + all members) 
    new_n_con_nodes.append([rn_id, forum_id])
    for person_id in group['nd']: # ici nd sont les ids des personnes (member) qui concernent un forum identifié par forum_id
        new_n_con_nodes.append([rn_id, person_id])
    
    # Node property: nbMember
    nb_members = len(group)
    new_node_props.append([rn_id, "nbMember", nb_members])

# Fonction  pour formater mess commande Cozo 
def format_cozo(rel, rows, cols):
    entries = ",".join(
        "[" + ",".join(f'"{x}"' if isinstance(x, str) else str(x) for x in row) + "]"
        for row in rows
    )
    return f"?[{','.join(cols)}] <- [{entries}] :put {rel} {{{','.join(cols)}}}"

# Chunked insertion 
def chunkify(lst, size):
    for i in range(0, len(lst), size):
        yield lst[i:i + size]

def run_chunks(rel, rows, cols):
    total = ceil(len(rows) / CHUNK_SIZE)
    for i, chunk in enumerate(chunkify(rows, CHUNK_SIZE), 1):
        print(f"[{rel}] chunk {i}/{total}")
        client.run(format_cozo(rel, chunk, cols))

#  Exécuter l'insertion 
run_chunks("reified_node", new_reified_nodes, ["id_rn"])
run_chunks("node_label", new_node_labels, ["id_n","ln"])
run_chunks("n_composed_of_node", new_n_con_nodes, ["id_rn","id_n"])
run_chunks("n_composed_of_edge", new_n_con_edges, ["id_rn","id_e"])
run_chunks("node_prop", new_node_props, ["id_n","key","value"])

print("\n voilà ! Les reified nodes forumMembership ont été créés avec succès")

[reified_node] chunk 1/8
[reified_node] chunk 2/8
[reified_node] chunk 3/8
[reified_node] chunk 4/8
[reified_node] chunk 5/8
[reified_node] chunk 6/8
[reified_node] chunk 7/8
[reified_node] chunk 8/8
[node_label] chunk 1/8
[node_label] chunk 2/8
[node_label] chunk 3/8
[node_label] chunk 4/8
[node_label] chunk 5/8
[node_label] chunk 6/8
[node_label] chunk 7/8
[node_label] chunk 8/8
[n_composed_of_node] chunk 1/170
[n_composed_of_node] chunk 2/170
[n_composed_of_node] chunk 3/170
[n_composed_of_node] chunk 4/170
[n_composed_of_node] chunk 5/170
[n_composed_of_node] chunk 6/170
[n_composed_of_node] chunk 7/170
[n_composed_of_node] chunk 8/170
[n_composed_of_node] chunk 9/170
[n_composed_of_node] chunk 10/170
[n_composed_of_node] chunk 11/170
[n_composed_of_node] chunk 12/170
[n_composed_of_node] chunk 13/170
[n_composed_of_node] chunk 14/170
[n_composed_of_node] chunk 15/170
[n_composed_of_node] chunk 16/170
[n_composed_of_node] chunk 17/170
[n_composed_of_node] chunk 18/170
[n_composed_of_node] chunk 19/170
[n_composed_of_node] chunk 20/170
[n_composed_of_node] chunk 21/170
[n_composed_of_node] chunk 22/170
[n_composed_of_node] chunk 23/170
[n_composed_of_node] chunk 24/170
[n_composed_of_node] chunk 25/170
[n_composed_of_node] chunk 26/170
[n_composed_of_node] chunk 27/170
[n_composed_of_node] chunk 28/170
[n_composed_of_node] chunk 29/170
[n_composed_of_node] chunk 30/170
[n_composed_of_node] chunk 31/170
[n_composed_of_node] chunk 32/170
[n_composed_of_node] chunk 33/170
[n_composed_of_node] chunk 34/170
[n_composed_of_node] chunk 35/170
[n_composed_of_node] chunk 36/170
[n_composed_of_node] chunk 37/170
[n_composed_of_node] chunk 38/170
[n_composed_of_node] chunk 39/170
[n_composed_of_node] chunk 40/170
[n_composed_of_node] chunk 41/170
[n_composed_of_node] chunk 42/170
[n_composed_of_node] chunk 43/170
[n_composed_of_node] chunk 44/170
[n_composed_of_node] chunk 45/170
[n_composed_of_node] chunk 46/170
[n_composed_of_node] chunk 47/170
[n_composed_of_node] chunk 48/170
[n_composed_of_node] chunk 49/170
[n_composed_of_node] chunk 50/170
[n_composed_of_node] chunk 51/170
[n_composed_of_node] chunk 52/170
[n_composed_of_node] chunk 53/170
[n_composed_of_node] chunk 54/170
[n_composed_of_node] chunk 55/170
[n_composed_of_node] chunk 56/170
[n_composed_of_node] chunk 57/170
[n_composed_of_node] chunk 58/170
[n_composed_of_node] chunk 59/170
[n_composed_of_node] chunk 60/170
[n_composed_of_node] chunk 61/170
[n_composed_of_node] chunk 62/170
[n_composed_of_node] chunk 63/170
[n_composed_of_node] chunk 64/170
[n_composed_of_node] chunk 65/170
[n_composed_of_node] chunk 66/170
[n_composed_of_node] chunk 67/170
[n_composed_of_node] chunk 68/170
[n_composed_of_node] chunk 69/170
[n_composed_of_node] chunk 70/170
[n_composed_of_node] chunk 71/170
[n_composed_of_node] chunk 72/170
[n_composed_of_node] chunk 73/170
[n_composed_of_node] chunk 74/170
[n_composed_of_node] chunk 75/170
[n_composed_of_node] chunk 76/170
[n_composed_of_node] chunk 77/170
[n_composed_of_node] chunk 78/170
[n_composed_of_node] chunk 79/170
[n_composed_of_node] chunk 80/170
[n_composed_of_node] chunk 81/170
[n_composed_of_node] chunk 82/170
[n_composed_of_node] chunk 83/170
[n_composed_of_node] chunk 84/170
[n_composed_of_node] chunk 85/170
[n_composed_of_node] chunk 86/170
[n_composed_of_node] chunk 87/170
[n_composed_of_node] chunk 88/170
[n_composed_of_node] chunk 89/170
[n_composed_of_node] chunk 90/170
[n_composed_of_node] chunk 91/170
[n_composed_of_node] chunk 92/170
[n_composed_of_node] chunk 93/170
[n_composed_of_node] chunk 94/170
[n_composed_of_node] chunk 95/170
[n_composed_of_node] chunk 96/170
[n_composed_of_node] chunk 97/170
[n_composed_of_node] chunk 98/170
[n_composed_of_node] chunk 99/170
[n_composed_of_node] chunk 100/170
[n_composed_of_node] chunk 101/170
[n_composed_of_node] chunk 102/170
[n_composed_of_node] chunk 103/170
[n_composed_of_node] chunk 104/170
[n_composed_of_node] chunk 105/170
[n_composed_of_node] chunk 106/170
[n_composed_of_node] chunk 107/170
[n_composed_of_node] chunk 108/170
[n_composed_of_node] chunk 109/170
[n_composed_of_node] chunk 110/170
[n_composed_of_node] chunk 111/170
[n_composed_of_node] chunk 112/170
[n_composed_of_node] chunk 113/170
[n_composed_of_node] chunk 114/170
[n_composed_of_node] chunk 115/170
[n_composed_of_node] chunk 116/170
[n_composed_of_node] chunk 117/170
[n_composed_of_node] chunk 118/170
[n_composed_of_node] chunk 119/170
[n_composed_of_node] chunk 120/170
[n_composed_of_node] chunk 121/170
[n_composed_of_node] chunk 122/170
[n_composed_of_node] chunk 123/170
[n_composed_of_node] chunk 124/170
[n_composed_of_node] chunk 125/170
[n_composed_of_node] chunk 126/170
[n_composed_of_node] chunk 127/170
[n_composed_of_node] chunk 128/170
[n_composed_of_node] chunk 129/170
[n_composed_of_node] chunk 130/170
[n_composed_of_node] chunk 131/170
[n_composed_of_node] chunk 132/170
[n_composed_of_node] chunk 133/170
[n_composed_of_node] chunk 134/170
[n_composed_of_node] chunk 135/170
[n_composed_of_node] chunk 136/170
[n_composed_of_node] chunk 137/170
[n_composed_of_node] chunk 138/170
[n_composed_of_node] chunk 139/170
[n_composed_of_node] chunk 140/170
[n_composed_of_node] chunk 141/170
[n_composed_of_node] chunk 142/170
[n_composed_of_node] chunk 143/170
[n_composed_of_node] chunk 144/170
[n_composed_of_node] chunk 145/170
[n_composed_of_node] chunk 146/170
[n_composed_of_node] chunk 147/170
[n_composed_of_node] chunk 148/170
[n_composed_of_node] chunk 149/170
[n_composed_of_node] chunk 150/170
[n_composed_of_node] chunk 151/170
[n_composed_of_node] chunk 152/170
[n_composed_of_node] chunk 153/170
[n_composed_of_node] chunk 154/170
[n_composed_of_node] chunk 155/170
[n_composed_of_node] chunk 156/170
[n_composed_of_node] chunk 157/170
[n_composed_of_node] chunk 158/170
[n_composed_of_node] chunk 159/170
[n_composed_of_node] chunk 160/170
[n_composed_of_node] chunk 161/170
[n_composed_of_node] chunk 162/170
[n_composed_of_node] chunk 163/170
[n_composed_of_node] chunk 164/170
[n_composed_of_node] chunk 165/170
[n_composed_of_node] chunk 166/170
[n_composed_of_node] chunk 167/170
[n_composed_of_node] chunk 168/170
[n_composed_of_node] chunk 169/170
[n_composed_of_node] chunk 170/170
[n_composed_of_edge] chunk 1/162
[n_composed_of_edge] chunk 2/162
[n_composed_of_edge] chunk 3/162
[n_composed_of_edge] chunk 4/162
[n_composed_of_edge] chunk 5/162
[n_composed_of_edge] chunk 6/162
[n_composed_of_edge] chunk 7/162
[n_composed_of_edge] chunk 8/162
[n_composed_of_edge] chunk 9/162
[n_composed_of_edge] chunk 10/162
[n_composed_of_edge] chunk 11/162
[n_composed_of_edge] chunk 12/162
[n_composed_of_edge] chunk 13/162
[n_composed_of_edge] chunk 14/162
[n_composed_of_edge] chunk 15/162
[n_composed_of_edge] chunk 16/162
[n_composed_of_edge] chunk 17/162
[n_composed_of_edge] chunk 18/162
[n_composed_of_edge] chunk 19/162
[n_composed_of_edge] chunk 20/162
[n_composed_of_edge] chunk 21/162
[n_composed_of_edge] chunk 22/162
[n_composed_of_edge] chunk 23/162
[n_composed_of_edge] chunk 24/162
[n_composed_of_edge] chunk 25/162
[n_composed_of_edge] chunk 26/162
[n_composed_of_edge] chunk 27/162
[n_composed_of_edge] chunk 28/162
[n_composed_of_edge] chunk 29/162
[n_composed_of_edge] chunk 30/162
[n_composed_of_edge] chunk 31/162
[n_composed_of_edge] chunk 32/162
[n_composed_of_edge] chunk 33/162
[n_composed_of_edge] chunk 34/162
[n_composed_of_edge] chunk 35/162
[n_composed_of_edge] chunk 36/162
[n_composed_of_edge] chunk 37/162
[n_composed_of_edge] chunk 38/162
[n_composed_of_edge] chunk 39/162
[n_composed_of_edge] chunk 40/162
[n_composed_of_edge] chunk 41/162
[n_composed_of_edge] chunk 42/162
[n_composed_of_edge] chunk 43/162
[n_composed_of_edge] chunk 44/162
[n_composed_of_edge] chunk 45/162
[n_composed_of_edge] chunk 46/162
[n_composed_of_edge] chunk 47/162
[n_composed_of_edge] chunk 48/162
[n_composed_of_edge] chunk 49/162
[n_composed_of_edge] chunk 50/162
[n_composed_of_edge] chunk 51/162
[n_composed_of_edge] chunk 52/162
[n_composed_of_edge] chunk 53/162
[n_composed_of_edge] chunk 54/162
[n_composed_of_edge] chunk 55/162
[n_composed_of_edge] chunk 56/162
[n_composed_of_edge] chunk 57/162
[n_composed_of_edge] chunk 58/162
[n_composed_of_edge] chunk 59/162
[n_composed_of_edge] chunk 60/162
[n_composed_of_edge] chunk 61/162
[n_composed_of_edge] chunk 62/162
[n_composed_of_edge] chunk 63/162
[n_composed_of_edge] chunk 64/162
[n_composed_of_edge] chunk 65/162
[n_composed_of_edge] chunk 66/162
[n_composed_of_edge] chunk 67/162
[n_composed_of_edge] chunk 68/162
[n_composed_of_edge] chunk 69/162
[n_composed_of_edge] chunk 70/162
[n_composed_of_edge] chunk 71/162
[n_composed_of_edge] chunk 72/162
[n_composed_of_edge] chunk 73/162
[n_composed_of_edge] chunk 74/162
[n_composed_of_edge] chunk 75/162
[n_composed_of_edge] chunk 76/162
[n_composed_of_edge] chunk 77/162
[n_composed_of_edge] chunk 78/162
[n_composed_of_edge] chunk 79/162
[n_composed_of_edge] chunk 80/162
[n_composed_of_edge] chunk 81/162
[n_composed_of_edge] chunk 82/162
[n_composed_of_edge] chunk 83/162
[n_composed_of_edge] chunk 84/162
[n_composed_of_edge] chunk 85/162
[n_composed_of_edge] chunk 86/162
[n_composed_of_edge] chunk 87/162
[n_composed_of_edge] chunk 88/162
[n_composed_of_edge] chunk 89/162
[n_composed_of_edge] chunk 90/162
[n_composed_of_edge] chunk 91/162
[n_composed_of_edge] chunk 92/162
[n_composed_of_edge] chunk 93/162
[n_composed_of_edge] chunk 94/162
[n_composed_of_edge] chunk 95/162
[n_composed_of_edge] chunk 96/162
[n_composed_of_edge] chunk 97/162
[n_composed_of_edge] chunk 98/162
[n_composed_of_edge] chunk 99/162
[n_composed_of_edge] chunk 100/162
[n_composed_of_edge] chunk 101/162
[n_composed_of_edge] chunk 102/162
[n_composed_of_edge] chunk 103/162
[n_composed_of_edge] chunk 104/162
[n_composed_of_edge] chunk 105/162
[n_composed_of_edge] chunk 106/162
[n_composed_of_edge] chunk 107/162
[n_composed_of_edge] chunk 108/162
[n_composed_of_edge] chunk 109/162
[n_composed_of_edge] chunk 110/162
[n_composed_of_edge] chunk 111/162
[n_composed_of_edge] chunk 112/162
[n_composed_of_edge] chunk 113/162
[n_composed_of_edge] chunk 114/162
[n_composed_of_edge] chunk 115/162
[n_composed_of_edge] chunk 116/162
[n_composed_of_edge] chunk 117/162
[n_composed_of_edge] chunk 118/162
[n_composed_of_edge] chunk 119/162
[n_composed_of_edge] chunk 120/162
[n_composed_of_edge] chunk 121/162
[n_composed_of_edge] chunk 122/162
[n_composed_of_edge] chunk 123/162
[n_composed_of_edge] chunk 124/162
[n_composed_of_edge] chunk 125/162
[n_composed_of_edge] chunk 126/162
[n_composed_of_edge] chunk 127/162
[n_composed_of_edge] chunk 128/162
[n_composed_of_edge] chunk 129/162
[n_composed_of_edge] chunk 130/162
[n_composed_of_edge] chunk 131/162
[n_composed_of_edge] chunk 132/162
[n_composed_of_edge] chunk 133/162
[n_composed_of_edge] chunk 134/162
[n_composed_of_edge] chunk 135/162
[n_composed_of_edge] chunk 136/162
[n_composed_of_edge] chunk 137/162
[n_composed_of_edge] chunk 138/162
[n_composed_of_edge] chunk 139/162
[n_composed_of_edge] chunk 140/162
[n_composed_of_edge] chunk 141/162
[n_composed_of_edge] chunk 142/162
[n_composed_of_edge] chunk 143/162
[n_composed_of_edge] chunk 144/162
[n_composed_of_edge] chunk 145/162
[n_composed_of_edge] chunk 146/162
[n_composed_of_edge] chunk 147/162
[n_composed_of_edge] chunk 148/162
[n_composed_of_edge] chunk 149/162
[n_composed_of_edge] chunk 150/162
[n_composed_of_edge] chunk 151/162
[n_composed_of_edge] chunk 152/162
[n_composed_of_edge] chunk 153/162
[n_composed_of_edge] chunk 154/162
[n_composed_of_edge] chunk 155/162
[n_composed_of_edge] chunk 156/162
[n_composed_of_edge] chunk 157/162
[n_composed_of_edge] chunk 158/162
[n_composed_of_edge] chunk 159/162
[n_composed_of_edge] chunk 160/162
[n_composed_of_edge] chunk 161/162
[n_composed_of_edge] chunk 162/162
[node_prop] chunk 1/8
[node_prop] chunk 2/8
[node_prop] chunk 3/8
[node_prop] chunk 4/8
[node_prop] chunk 5/8
[node_prop] chunk 6/8
[node_prop] chunk 7/8
[node_prop] chunk 8/8

 voilà ! Les reified nodes forumMembership ont été créés avec succès

In [3]:
res = client.run("?[n, l]:= *node_label[n, l], l='forumMembership'")
res

                    n                l
0      35184376285345  forumMembership
1      35184376285346  forumMembership
2      35184376285347  forumMembership
3      35184376285348  forumMembership
4      35184376285349  forumMembership
...               ...              ...
79465  35184376364810  forumMembership
79466  35184376364811  forumMembership
79467  35184376364812  forumMembership
79468  35184376364813  forumMembership
79469  35184376364814  forumMembership

[79470 rows x 2 columns]

In [10]:
res = client.run("?[n, val]:= *node_prop[n, 'nbMember',val], :order -val")
res

                    n  val
0      35184372518647  340
1      35184372522503  338
2      35184372511777  269
3      35184372517688  256
4      35184372512372  230
...               ...  ...
11072  35184372522536    1
11073  35184372522539    1
11074  35184372522542    1
11075  35184372522543    1
11076  35184372522545    1

[11077 rows x 2 columns]

In [4]:
#query : 
q1=""" 
# Filtrer les forumMembership avec nbMember > 3
filtered_forum[n_rn] :=
    *node_prop[n_rn, 'nbMember', nb],
    nb > 150

# Récupérer les personnes qui font partie du forumMembership
forum_member[n_rn, person] :=
    filtered_forum[n_rn],
    *n_composed_of_node[n_rn, person],
    *node_label[person, 'person']

# Récupérer leur locationIP
member_ip[person, ip] :=
    forum_member[n_rn, person],
    *node_prop[person, 'locationIP', ip]

# Résultat final
?[person, ip] := member_ip[person, ip]

"""
# print(client.run(q1))

In [5]:
#query : 
q2=""" 
# Filtrer les forumMembership avec nbMember > 3
filtered_forum[n_rn] :=
    *node_prop[n_rn, 'nbMember', nb],
    nb <150

# Récupérer les personnes qui font partie du forumMembership
forum_member[n_rn, person] :=
    filtered_forum[n_rn],
    *n_composed_of_node[n_rn, person],
    *node_label[person, 'person']

# Récupérer leur locationIP
member_ip[person, ip] :=
    forum_member[n_rn, person],
    *node_prop[person, 'locationIP', ip]

# Résultat final
?[person, ip] := member_ip[person, ip]

"""
# print(client.run(q2))

In [7]:
import time
# exécuter 10 fois auto 
n = 10
times = []

for _ in range(n):
    start = time.time()  
    client.run(q2)
    end = time.time()  
    times.append((end - start) * 1000)  # en ms

mean = sum(times) / n
print(f"Temps moyen sur {n} exécutions : {mean:.3f} ms")

Temps moyen sur 10 exécutions : 15280.674 ms